Repository KnowckknowcK/FE, pull requests merged in 2024-05, with the labels that each got.

#36 CSS: 지문 조회 페이지 디자인 개선
  public/index.html
  src/App.css
  src/components/bottomNavBar/bottomNavBar.module.css
  src/index.css
  src/index.js
  src/page/literacy/Article.jsx
  src/page/literacy/Article.module.css
  src/page/literacy/ArticleList.jsx
  src/page/literacy/ArticleList.module.css
  src/page/literacy/SummaryWriting.jsx
  src/page/literacy/SummaryWriting.module.css
  src/page/main/Main.jsx
  src/util/FormatDateTime.js
Labels: 🎨 Html&css

#42 Feat/issue-#28 로그인 페이지 구현
  public/check_icon.png
  public/email.png
  public/img/web_neutral_rd_ctn@3x.png
  public/warning_icon.png
  src/page/signup&in/SignIn.css
  src/page/signup&in/SignIn.jsx
  src/page/signup&in/SignIn.module.css
Labels: ✨ Feature

#51 Feat: 프로필 페이지
  package-lock.json
  package.json
  src/App.js
  src/components/bottomNavBar/bottomNavBar.jsx
  src/page/literacy/Article.jsx
  src/page/literacy/Article.module.css
  src/page/literacy/ArticleList.jsx
  src/page/literacy/OpinionWriting.jsx
  src/page/literacy/SummaryWriting.jsx
  src/page/literacy/SummaryWriting.module.css
  src/page/user/UserInfo.css
  src/page/user/UserInfo.jsx
  src/page/user/UserInfo.module.css
  src/util/userId.js
Labels: ✨ Feature

#52 Feat/issue #41 회원가입 페이지
  src/page/signup&in/SignIn.jsx
  src/page/signup&in/SignUp.css
  src/page/signup&in/SignUp.jsx
  src/page/signup&in/SignUp.module.css
Labels: ✨ Feature

#54 Design: 로그인/회원가입 페이지 GlobalStyle 적용
  src/page/signup&in/SignIn.module.css
  src/page/signup&in/SignUp.module.css
  src/styles/GlobalStyle.jsx
Labels: 🎨 Html&css

#57 Feat/issue #55
  src/page/signup&in/EmailCheck.jsx
  src/page/signup&in/EmailCheck.module.css
  src/page/signup&in/SignUp.jsx
  src/page/signup&in/SignUp.module.css
Labels: ✨ Feature

#59 Feat: 프로필 수정 페이지
  package-lock.json
  package.json
  src/App.js
  src/components/bottomNavBar/bottomNavBar.jsx
  src/lib/customAxios.js
  src/page/literacy/ArticleList.jsx
  src/page/literacy/Feedback.jsx
  src/page/literacy/OpinionFeedback.jsx
  src/page/literacy/OpinionWriting.jsx
  src/page/literacy/SummaryWriting.jsx
  src/page/main/Main.jsx
  src/page/user/ProfileUpdate.jsx
  src/page/user/UserInfo.jsx
  src/page/user/UserInfo.module.css
Labels: ✨ Feature, 🎨 Html&css

#60 Fix/issue #58 회원가입 formData 형식으로 수정
  src/page/signup&in/SignUp.jsx
Labels: 🐞 BugFix

#66 Feat/issue #65
  src/App.js
  src/page/signup&in/GoogleLoginSuccess.jsx
  src/page/signup&in/SignIn.jsx
  src/page/signup&in/Spinner.module.css
Labels: ✨ Feature

#67 CSS: 지문 언더바 중앙으로 조정 및 CSS 수정 / 페이지바 수정
  src/page/literacy/Article.module.css
  src/page/literacy/ArticleList.jsx
  src/page/literacy/ArticleList.module.css
  src/page/user/UserInfo.jsx
  src/page/user/UserInfo.module.css
Labels: 🐞 BugFix, 🎨 Html&css

#72 🎨 CSS: 요약/견해 피드백,작성 페이지 전반
  src/page/literacy/Feedback.jsx
  src/page/literacy/Feedback.module.css
  src/page/literacy/OpinionFeedback.jsx
  src/page/literacy/OpinionWriting.jsx
  src/page/literacy/SummaryWriting.jsx
  src/page/literacy/SummaryWriting.module.css
Labels: 🎨 Html&css

#76 Feat/issue #75
  src/App.js
  src/page/literacy/Article.jsx
  src/page/literacy/Article.module.css
  src/page/literacy/OpinionWriting.jsx
  src/page/user/ProfileUpdate.jsx
  src/page/user/UserInfo.module.css
Labels: ✨ Feature

#88 Fix: 마이페이지 스크롤 / 피드백 로딩 스피너 추가
  src/page/literacy/Feedback.jsx
  src/page/literacy/Feedback.module.css
  src/page/literacy/OpinionFeedback.jsx
  src/page/literacy/OpinionWriting.jsx
  src/page/literacy/SummaryWriting.jsx
  src/page/literacy/SummaryWriting.module.css
  src/page/main/RecommendedItem.jsx
  src/page/user/UserInfo.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#90 Fix: 프로필 사진 수정 시 변경 취소 오류
  src/page/user/ProfileUpdate.jsx
Labels: 🐞 BugFix

#94 Fix: 지문 목록 리스트 로딩 스피너 추가 / 견해 입장 선택 radio btn 추가
  src/page/literacy/Article.jsx
  src/page/literacy/ArticleList.jsx
  src/page/literacy/ArticleList.module.css
  src/page/literacy/Feedback.jsx
  src/page/literacy/OpinionFeedback.jsx
  src/page/literacy/OpinionWriting.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#98 Fix : navigate 에러
  src/page/user/Summary/SummaryHistoryIng.jsx
Labels: 🐞 BugFix

#97 Feat: 문해력 피드백 페이지 경험치 추가
  src/page/literacy/Feedback.jsx
  src/page/literacy/Feedback.module.css
  src/page/literacy/OpinionFeedback.jsx
Labels: ✨ Feature

#105 Fix: 견해 피드백에서 토론방 이동 시 api 추가
  src/page/literacy/OpinionFeedback.jsx
  src/page/literacy/SummaryWriting.jsx
Labels: 🐞 BugFix, 📬 API

#113 Feat/issue #100
  src/page/literacy/Article.module.css
  src/page/literacy/Feedback.module.css
  src/page/literacy/OpinionWriting.jsx
  src/page/literacy/SummaryWriting.jsx
  src/page/literacy/SummaryWriting.module.css
  src/page/user/ProfileUpdate.jsx
  src/page/user/UserInfo.jsx
Labels: 🐞 BugFix, ✨ Feature

#115 🎨 Style: 문해력 진단 페이지 버튼 색 통일
  src/page/literacy/SummaryWriting.module.css
Labels: 🎨 Html&css

#116 Feat/issue #103
  src/App.js
  src/page/dashboard/Dashboard.jsx
  src/page/dashboard/Dashboard.module.css
  src/page/dashboard/Donut.jsx
  src/page/dashboard/Spinner.module.css
  src/page/user/MyDebateRoomList.jsx
  src/page/user/Opinion/OpinionDetailPage.jsx
  src/page/user/Opinion/OpinionHistory.jsx
  src/page/user/Spinner.module.css
  src/page/user/Summary/SummaryHistoryDone.jsx
  src/page/user/Summary/SummaryHistoryIng.jsx
  src/page/user/UserInfo.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#117 !HOTFIX: 플러그인이 도넛차트 전역으로 설정되는 현상 수정
  src/page/dashboard/Donut.jsx
Labels: 🐞 BugFix

#119 Feat/issue #103
  src/page/user/MoveBackButton.jsx
  src/page/user/MyDebateRoomList.jsx
  src/page/user/MyDebateRoomList.module.css
  src/page/user/Opinion/MyOpinion.module.css
  src/page/user/Opinion/Opinion.jsx
  src/page/user/Opinion/Opinion.module.css
  src/page/user/Opinion/OpinionContext.jsx
  src/page/user/Opinion/OpinionDetailPage.jsx
  src/page/user/Opinion/OpinionHistory.jsx
  src/page/user/Opinion/OpinionHistory.module.css
  src/page/user/Summary/SummaryDetail.module.css
  src/page/user/Summary/SummaryDetailPage.jsx
  src/page/user/Summary/SummaryHistory.module.css
  src/page/user/Summary/SummaryHistoryDone.jsx
  src/page/user/Summary/SummaryHistoryIng.jsx
Labels: 🎨 Html&css

#120 Feat: 참여 이력이 없을 경우 페이지 보여주기
  public/bulb.png
  src/page/user/MyDebateRoomList.jsx
  src/page/user/Opinion/OpinionHistory.jsx
  src/page/user/Summary/SummaryHistoryDone.jsx
  src/page/user/Summary/SummaryHistoryIng.jsx
  src/page/user/noWork/NoWork.jsx
  src/page/user/noWork/NoWork.module.css
Labels: 🎨 Html&css

#122 🎨 Style: AI 피드백 페이지 내용 max-height 지정
  src/page/literacy/Feedback.jsx
  src/page/literacy/Feedback.module.css
  src/page/literacy/OpinionFeedback.jsx
Labels: 🎨 Html&css

#124 Feat/issue #123
  src/lib/customAxios.js
  src/page/signup&in/GoogleLoginSuccess.jsx
  src/page/signup&in/SignIn.jsx
Labels: ✨ Feature

#132 Fix: 견해 피드백에서는 점수 제거
  src/page/literacy/OpinionFeedback.jsx
Labels: 🐞 BugFix

#136 Feat/issue #135
  public/arrow.png
  src/page/dashboard/Dashboard.jsx
  src/page/user/Opinion/MyOpinion.module.css
  src/page/user/Opinion/Opinion.jsx
  src/page/user/Opinion/Opinion.module.css
  src/page/user/Opinion/OpinionDetailPage.jsx
  src/page/user/Summary/Summary.jsx
  src/page/user/Summary/SummaryDetail.module.css
  src/page/user/Summary/SummaryDetailPage.jsx
  src/page/user/Summary/SummaryHistoryDone.jsx
  src/util/FormatDateTime.js
Labels: ✨ Feature

#138 !HOFIX: 견해에서 토론방 이동 로직 수정
  src/page/user/Opinion/OpinionDetailPage.jsx
Labels: 🐞 BugFix

#139 Feat/issue #135
  src/App.js
  src/page/literacy/ArticleList.jsx
  src/page/user/Opinion/OpinionDetailPage.jsx
  src/page/user/Opinion/OpinionHistory.jsx
  src/util/ScrollToTop.js
Labels: ✨ Feature

#140 Style: 페이지 별 CSS 조정
  src/page/literacy/Article.jsx
  src/page/literacy/Article.module.css
  src/page/literacy/ArticleList.jsx
  src/page/literacy/Feedback.jsx
  src/page/literacy/Feedback.module.css
  src/page/literacy/SummaryWriting.jsx
  src/page/literacy/SummaryWriting.module.css
  src/page/user/ProfileUpdate.jsx
  src/page/user/UserInfo.jsx
Labels: 🎨 Html&css

#143 Fix: 로그아웃 버튼 삭제
  src/page/user/UserInfo.jsx
Labels: 🐞 BugFix

#149 Fix: @gamil.com 외의 메일로 구글 로그인 가능하도록 수정
  src/page/signup&in/GoogleLoginSuccess.jsx
Labels: 🐞 BugFix

#151 Feat/issue #150
  src/page/dashboard/Dashboard.jsx
  src/page/dashboard/Dashboard.module.css
  src/page/user/MyDebateRoomList.jsx
  src/page/user/Opinion/MyOpinion.module.css
  src/page/user/ProfileUpdate.jsx
  src/page/user/Summary/SummaryDetail.module.css
  src/page/user/Summary/SummaryHistoryIng.jsx
Labels: 🐞 BugFix, 🎨 Html&css

#153 Fix: 사용자 피드백 반영
  package-lock.json
  package.json
  public/img/buttonImg1.png
  public/img/buttonImg1.webp
  public/img/shapeImg.png
  public/img/shapeImg.webp
  public/img/web_neutral_rd_ctn@3x.png
  public/img/web_neutral_rd_ctn_3x.webp
  public/index.html
  public/loading.png
  public/loading.webp
  public/logo192.png
  public/logo192.webp
  public/logo512.png
  src/page/literacy/Article.jsx
  src/page/literacy/Article.module.css
  src/page/literacy/ArticleList.jsx
  src/page/literacy/ArticleSkeleton.jsx
  src/page/literacy/Feedback.jsx
  src/page/literacy/Feedback.module.css
  src/page/literacy/SummaryWriting.module.css
  src/page/main/Main.jsx
  src/page/signup&in/SignIn.jsx
  src/page/user/ProfileUpdate.jsx
  src/page/user/UserInfo.jsx
  src/page/user/UserInfo.module.css
Labels: 🐞 BugFix, 🎨 Html&css

#155 !HOTFIX : webp 변환 manfest.json에서 적용
  public/manifest.json
Labels: 🐞 BugFix
